//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License_Categories
    {
        public int Id { get; set; }
        public int License_Id { get; set; }
        public int Categorie_Id { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual License License { get; set; }
    }
}
