//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_History
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Change_Date { get; set; }
        public Nullable<int> License_Id { get; set; }
        public string Commentary { get; set; }
    
        public virtual License License { get; set; }
    }
}
